export const ANIMATION = {
  // OCR Scan Overlay
  OCR_STAGE_DELAY_MS: 800,
  SCAN_LINE_DURATION_MS: 1000,
  SCAN_LINE_TRAVEL_DISTANCE: 236,
  SPINNER_DURATION_MS: 800,
  TEXT_FADE_OUT_MS: 150,
  TEXT_FADE_IN_MS: 250,
  SUCCESS_NAV_DELAY_MS: 500,

  // Previews
  PREVIEW_SPRING_DAMPING: 20,
  PREVIEW_SPRING_STIFFNESS: 150,
  PREVIEW_FADE_OUT_MS: 250,
  PREVIEW_RETAKE_FADE_OUT_MS: 200,
  PREVIEW_RETAKE_DELAY_MS: 100,

  // Camera
  FLASH_IN_MS: 50,
  FLASH_OUT_MS: 400,

  // Form Submission
  SUBMIT_DELAY_MS: 1500,
};